Refactoring
FavoriitePrime/Eternal pull request #1
Opened 2023-03-01 10:54 UTC by FavoriitePrime

2023-03-01 11:52 UTC, KonstaKun requested changes

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/Interfaces/IMoveabel.cs
> +public interface IMoveabel
Опечатка

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/Interfaces/IMoveabel.cs
> +
Пустая строчка

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/Interfaces/IPlayerInput.cs
> +    float GetVeritcalInput();
Возвращай вектор, в котором X отвечает за горизонтальный ввод, а Y - вертикальный, вместо двух методов

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/PlayerMoveDirection.cs
> +        direction.y = _input.GetJumpInput(groundCheck);
Название функции не отвечает за то, что она делает. Кроме движения ты еще и вызываешь метод прыжка, который еще и почему-то зависит от граундчека.

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/Interfaces/IPlayerInput.cs
> +    int GetJumpInput(bool groundCheck);
Ввод не должен зависеть от каких-то других параметров

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/PlayerMovement.cs
> +    public void Move(PlayerMoveDirection input)
Move(Vector2 direction), не нужно сетить туда целый класс

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/PlayerMovement.cs
> +    public void Rotate(PlayerInput input)
Rotate(Vector3 rotation), не нужно сетить туда целый класс

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/PlayerMoveDirection.cs
> +public class PlayerMoveDirection : MonoBehaviour
Не очень понимаю смысл в этом компоненте, ты можешь все манипуляции с преобразованием координат сделать в самом Player

2023-03-01 11:52 UTC, KonstaKun commented on Assets/Player/PlayerMovement.cs
> +        direction.z *= _speed;
Раздели функции прыжка и перемещения на две, код станет чище и понятнее

2023-03-01 12:03 UTC, FavoriitePrime commented on Assets/Player/Interfaces/IMoveabel.cs
> +public interface IMoveabel
Исправил

2023-03-01 12:04 UTC, FavoriitePrime commented on Assets/Player/Interfaces/IMoveabel.cs
> +
Исправил

2023-03-01 12:07 UTC, FavoriitePrime commented on Assets/Player/Interfaces/IPlayerInput.cs
> +    float GetVeritcalInput();
Готово

2023-03-05 14:58 UTC, FavoriitePrime commented on Assets/Player/Interfaces/IPlayerInput.cs
> +    int GetJumpInput(bool groundCheck);
Исправил

2023-03-05 14:59 UTC, FavoriitePrime commented on Assets/Player/PlayerMovement.cs
> +    public void Move(PlayerMoveDirection input)
Исправил

2023-03-05 14:59 UTC, FavoriitePrime commented on Assets/Player/PlayerMovement.cs
> +    public void Rotate(PlayerInput input)
Исправил

2023-03-06 08:03 UTC, merged